edi:
  senderId: 108973090
  receiverId: 2123867180
  standardsIdentifier: U
  versionNumber: "00401"
  controlNumber: "000010154"
  ackRequested: 0
  usageIndicator: P

  functionalIdentifierCode: IB
  groupControlNumber: 10154
  agencyCode: X
  industryCode: "004010"

  transactionIdentifierCode: 846
  transactionSetControlNumber: 21847

  transactionSetPurposeCode: "00"
  reportTypeCode: SI
  biaReferenceIdentification: 1234567

  referenceIdentificationQualifier: IA
  referenceIdentification: 176

  entityIdentifierCode: VN

  productIdQualifier: UP
  productIdQualifierForVendor: VP

  itemDescriptionType: F
  productCharacteristicCode: 08
  productCharacteristicCodeForBuyer: 75
  priceIdentifyingCode: DIS

  quantityQualifier: 33
  unitCode: EA

  dateTimeQualifier: 018

  TransactionTotal: 0

  NumberOfIncludedSegments: 3984
  TransactionSetControl: 21847

  NumberOfTransactionSetIncluded: 1
  GroupControlNumber: 10154

  NumberOfFunctionalGroups: 1
  InterchangeControlNumber: "000010154"